# 用于dev
#FROM nvidia/cuda:11.2.0-cudnn8-devel-ubuntu18.04
# 用于prod
FROM nvidia/cuda:11.2.0-cudnn8-runtime-ubuntu20.04
LABEL maintainer="HGF"
LABEL repository="hgfkeep"

RUN apt update && \
    apt install -y bash \
                   build-essential \
                   curl \
                   ca-certificates \
                   python3 \
                   python3-pip && \
    rm -rf /var/lib/apt/lists
RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir \
    torch==1.9.0+cu102 --extra-index-url https://download.pytorch.org/whl/cu102